import { readFileSync } from 'node:fs';
import { DEFAULT_EQR, validateEquity, type EquityData } from '../src/model';
import { loadFlops } from '../src/postflop';
import { DEFAULT_DCFR, PreflopSolver } from '../src/solver';
import { loadThreeWay } from '../src/threeway';
import { buildTree, DEFAULT_TREE } from '../src/tree';
const eq = JSON.parse(readFileSync(new URL('../../equity/equity169.json', import.meta.url), 'utf8')) as EquityData;
validateEquity(eq);
const tw = loadThreeWay(readFileSync(new URL('../../equity/equity3.bin.gz', import.meta.url)));
const fl = loadFlops(readFileSync(process.argv[2]!));
const s = new PreflopSolver(buildTree(DEFAULT_TREE), eq, { ...DEFAULT_EQR, k: 1.25, m: 0.16 }, DEFAULT_DCFR, tw, fl, 2, Number(process.argv[4] ?? 99));
console.log('pamięć postflop MB', (s.postflop!.memoryBytes() / 1e6).toFixed(0), 'terminale', s.postflop!.terminals.length);
const n = Number(process.argv[3] ?? 5);
let t0 = Date.now();
for (let i = 0; i < n; i++) s.step();
console.log('s/iterację', ((Date.now() - t0) / 1000 / n).toFixed(2));
t0 = Date.now();
const e = s.exploitability();
console.log('exploitability s', ((Date.now() - t0) / 1000).toFixed(1), e.nashConv.toFixed(4));
let tot = 0; for (let p = 0; p < 6; p++) tot += s.value(p);
console.log('suma wartości graczy (−rake)', tot.toFixed(5));
